AllCops:
  RunRailsCops: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'public/**/*'
Metrics/LineLength:
  Max: 120